/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {


    public static int[] roll(int n) {

        int[] resultsArr = new int[n];

        for(int i = 0; i < resultsArr.length; i++){
            int randomRoll = (int)(Math.random() * 6 + 1);
            resultsArr[i] = randomRoll;
        }

        return resultsArr;
    }

}
