/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class BitMapTransformer {

    public static void main(String[] args){
        // pass args into constructor
        // according to the methods specified in the class
        // perform some transforms on the data according to
    }



}
