import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Path;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class BitMapTransformer {

    public static void main(String[] args){

        // read file and create a new this field which contains our bitmap data
        String bitPath = "resources/test.BMP";
        String savePath = "resources/flipVertically.BMP";

        // create new Bitmap instantiation upon which we will do some work
        // will eventually take in an output file path and a transform type
        Bitmap myBitmap = new Bitmap(bitPath, savePath);

//         myBitmap.mirrorOverHorizontalMidline();

//        myBitmap.mirrorOverVerticalMidline();

//        myBitmap.flipHorizontally();

        myBitmap.flipVertically();

        myBitmap.save();

    }



}
