/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class RestaurantTest {


    @Test public void testToStringWithRestaurant() {

        Restaurant newRestaurant = new Restaurant("Banana Leaf", 5, "$");
        assertTrue("numStars should be the same as Integer.toString()", newRestaurant.toString().equals(Integer.toString(newRestaurant.getStars())));

        int testInt = 5;
        assertTrue("numStars should be the same as testInt", newRestaurant.toString().equals(Integer.toString(testInt)));

        int testIntFalse = 6;
        assertFalse("numStars should not be the same as testIntFalse", newRestaurant.toString().equals(Integer.toString(testIntFalse)));
    }


    @Test public void testToStringWithReview() {

        Review newReview= new Review("Le'gooooo!", "Me", 5);
        assertTrue("numStars should be the same as Integer.toString()", newReview.toString().equals(Integer.toString(newReview.getStars())));

        int testInt = 5;
        assertTrue("numStars should be the same as testInt", newReview.toString().equals(Integer.toString(testInt)));

        int testIntFalse = 6;
        assertFalse("numStars should not be the same as testIntFalse", newReview.toString().equals(Integer.toString(testIntFalse)));
    }


    @Test public void testAddReview() {

        /////////// -- Test without adding

        Restaurant newRestaurant = new Restaurant("Seoul Food", 5,"$$");
        assertTrue("numStars avg should equal five after instantiation", 5 == newRestaurant.getStars());



        /////////// -- 1st Review test

        Review testReview = new Review("So, so good.", "D$", 8);
        newRestaurant.addReview(testReview);
        assertTrue("numStars avg should hit 6 after first review", 6 == newRestaurant.getStars());



        /////////// -- 2nd Review test

        Review testReview2 = new Review("Don't get me started.", "D$", 18);
        newRestaurant.addReview(testReview2);

        assertTrue("numStars avg should rise to 10 after review", 10 == newRestaurant.getStars());



        /////////// -- Duplicate Review test

        // add the same review again
        newRestaurant.addReview(testReview2);

        assertTrue("numStars avg should stay at 10 after adding duplicate review", 10 == newRestaurant.getStars());


    }
}
