

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Linter {
    public static void main(String[] args){

    }

    public static void alertSemicolons(){

        }
    }
}
